version: '2' 

services:
   todoApp:
    image: 'ganesh2292/todospring:1.0'
    ports:
      - "8080:8080"
    build:
      context: .
    container_name: todoApp
    depends_on: 
      - postgresDB
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresDB:5432/todo
      - SPRING_DATASOURCE_USERNAME=springjpa
      - SPRING_DATASOURCE_PASSWORD=Test@123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      
   
   postgresDB:
      image: 'postgres:13.1-alpine'
      container_name: postgresDB
      ports:
        - "33306:5432"
      environment:
        - POSTGRES_USER=springjpa
        - POSTGRES_PASSWORD=Test@123
        - POSTGRES_DB=todo
    
    